instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: jenkins-master
    properties:
      jenkins:
        admin:
          email: admin@localhost
          password: ((jenkins_admin_password))
        agent:
          password: ((jenkins_agent_password))
        server:
          address: http://localhost:8080/
    release: buildstack
  name: jenkins-master
  networks:
  - name: default
  persistent_disk_pool: 100GB
  stemcell: default
  vm_extensions:
  - internet-required
  - jenkins-pool
  vm_type: default
- azs:
  - z1
  - z2
  instances: 2
  jobs:
  - name: jenkins-slave
    properties:
      jenkins:
        slave:
          executors: 2
          labels: build
          master_password: ((jenkins_agent_password))
          master_username: agent
          mode: exclusive
      nexus:
        admin:
          password: ((nexus_admin_password))
          username: admin
        deployer:
          password: ((nexus_deployer_password))
          username: jenkins
    release: buildstack
  name: jenkins-slave
  networks:
  - name: default
  stemcell: default
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: nexus
    properties:
      nexus:
        admin:
          password: ((nexus_admin_password))
        deployer:
          password: ((nexus_deployer_password))
    release: buildstack
  name: nexus
  networks:
  - name: default
  stemcell: default
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: sonarqube
    properties:
      sonar:
        mysql:
          host: ((buildstack_db_instance_ip))
          password: ((sonar_mysql_password))
        server:
          address: ((sonar_server_address))
          port: ((sonar_server_port))
    release: buildstack
  name: sonarqube
  networks:
  - name: default
  stemcell: default
  vm_extensions:
  - internet-required
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: gerrit
    properties:
      gerrit:
        mysql:
          host: ((buildstack_db_instance_ip))
          password: ((gerrit_mysql_password))
    release: buildstack
  name: gerrit
  networks:
  - name: default
  persistent_disk_pool: 100GB
  stemcell: default
  vm_extensions:
  - internet-required
  vm_type: default
name: buildstack
releases:
- name: buildstack
  sha1: 1df89fc5db2d3d0b69aac85214f9b69cfa5af957
  url: https://storage.googleapis.com/finkit-buildstack-releases/releases/buildstack-boshrelease-0.0.17.tgz
  version: 0.0.17
stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3541.9"
update:
  canaries: 1
  canary_watch_time: 15000-300000
  max_in_flight: 1
  update_watch_time: 15000-300000
variables:
- name: jenkins_admin_password
  type: password
- name: jenkins_agent_password
  type: password
- name: nexus_admin_password
  type: password
- name: nexus_deployer_password
  type: password
- name: sonar_mysql_password
  type: password
- name: gerrit_mysql_password
  type: password

